# Generated by Django 4.1.5 on 2023-01-09 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_category',
            field=models.CharField(choices=[('bonus', 'Бонусная'), ('credit', 'Кредитная'), ('debit', 'Дебетовая')], default='bonus', max_length=50, verbose_name='Категория карты'),
        ),
    ]
