# Generated by Django 4.1.5 on 2023-01-09 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_alter_card_options_card_slug'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='card',
            table='card',
        ),
    ]
