# Generated by Django 4.1.5 on 2023-01-10 12:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_alter_card_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Инстина, если карта удалена', verbose_name='Удаленная карта'),
        ),
        migrations.CreateModel(
            name='CardHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата операции')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='Комментарий')),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_history', to='card.card', verbose_name='Карта')),
            ],
            options={
                'verbose_name': 'История операций с картой',
                'verbose_name_plural': 'История операций с картами',
                'db_table': 'card_history',
            },
        ),
    ]
