# Generated by Django 4.1.5 on 2023-01-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_card_deleted_cardhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.CharField(blank=True, help_text='CVV должен состоять из 3 цифр', max_length=3, null=True, verbose_name='CVV'),
        ),
        migrations.AlterField(
            model_name='card',
            name='pin',
            field=models.CharField(blank=True, help_text='PIN должен состоять из 4 цифр', max_length=4, null=True, verbose_name='PIN'),
        ),
    ]
