# Generated by Django 4.1.5 on 2023-01-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_alter_card_cvv_alter_card_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='payment_system',
            field=models.CharField(blank=True, choices=[('visa', 'Visa'), ('mastercard', 'MasterCard'), ('mir', 'Мир'), ('american_express', 'American Express')], help_text='Выберите платежную систему', max_length=20, null=True, verbose_name='Платежная система'),
        ),
    ]
